const profaneWords = [
  "shit",
  "fuck",
  "nigga",
  "arsehole",
  "asshat",
  "asshole",
  "bastard",
  "big black cock",
  "bitch",
  "bloody",
  "blowjob",
  "bollocks",
  "bugger",
  "bullshit",
  "chicken shit",
  "clusterfuck",
  "cock",
  "cocksucker",
  "coonass",
  "cornhole",
  "cracker",
  "cunt",
  "damn",
  "dick",
  "enshittification",
  "faggot",
  "feck",
  "fuck her right in the pussy",
  "fuck joe biden",
  "fuck, marry, kill",
  "fuckery",
  "grab 'em by the pussy",
  "healslut",
  "jesus fucking christ",
  "kike",
  "motherfucker",
  "nigger",
  "use of nigger in proper names",
  "paki",
  "poof",
  "poofter",
  "prick",
  "pussy",
  "ratfucking",
  "retard",
  "russian warship, go fuck yourself",
  "shit happens",
  "shithouse",
  "shitposting",
  "shitter",
  "shut the fuck up",
  "shut the hell up",
  "slut",
  "son of a bitch",
  "spic",
  "taking the piss",
  "twat",
  "unclefucker",
  "wanker",
  "whore",
  "tangina mo",
  "tangina",
  "putangina",
  "bobo",
  "tanga",
  "unitil",
  "mangmang",
  "gago",
  "ulol",
  "tarantado",
  "punyeta",
  "buwisit",
  "kupal",
  "walang kang kwenta",
  "lintik",
  "hinayupak",
  "puta",
  "pakshet",
  "leche",
  "walang hiya",
  "hudas",
  "siraulo",
  "animal ka",
  "anemal ka"
  
];

export default profaneWords;
